services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    entrypoint: ["./entrypoint.sh"]

  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: book_shop
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  db_data:
